all:
	g++ -o usb_test          usb_test.c

clean:
	rm -f usb_test


help:
	@echo	'make		would compile all source programs in this directory
	@echo	'make clean	would remove all object code in this directory
